### ISSUE TITLE
Open files on Microsoft OneDrive

### ISSUE THREAD

**Issue by LordWolfenstein** [Alex2772/editorpp#1]
When I preview text files on my OneDrive I can get a list of apps to open it with when I click "open in another app". Editor++ is not on that list. According to the internet, this feature have to be hard coded in to the app for me to be able to directly open files on my OneDrive without downloading the files first.

**Comment by Alex2772** [comment]
> According to the internet, this feature have to be hard coded in to the app

May you provide a link to a webpage describing this please? The only one I've found is the Microsoft's OneDrive SDK, which is quite unsuitable for my application.
